name: Dockerized Python application test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: run tests
        run: |
<<<<<<< HEAD
          poetry run pytest
=======
          docker run api pytest tests
>>>>>>> d3e04ed6d3f856a7166c47bd4867aba60bd85e40
